version: "3.4"

services:
  pych-tester:
    image: pychtester
    container_name: pych-tester-1
    restart: on-failure # or 'always'
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - clickhouse-server
  clickhouse-server:
    hostname: clickhost
    image: "clickhouse/clickhouse-server:latest"
    container_name: clickhouse-server-1
    ports:
      - 8123:8123 # http port
      - 9000:9000 # native port
      - 9009:9009 #
