[project]
name = "oscar"
version = "0.1.0"
description = "Oscar is an in-memory database with a single user transaction support"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.4.1",
]
